### ISSUE TITLE
Accessing ESP32 via serial communication to connect esptool and read/update firmware.

### ISSUE THREAD

**Issue by michalpasztamobica** [d-kato/GR-Boards_ESP32_Serial_Bridge#1]
Hello,

I am trying to connect to ESP32 chip on GR-LYCHEE in order to check the current firmware version (and update it if neccessary) using the esptool. I found this repository and also [GR-LYCHEE_ESP32_Serial_Bridge](https://github.com/d-kato/GR-LYCHEE_ESP32_Serial_Bridge), but neither of them worked for me. I tried both the precompiled binaries and compiling and flashing the device on my own. 

The UART peripheral never sent any information and was never recognized by the ESP tool. Looking at the [circuit schematic](https://www.core.co.jp/solution/m2m/gr-lychee/pdf/history/gr-lychee_circuit_b.pdf) and the [datasheet](https://www.renesas.com/eu/en/doc/products/mpumcu/doc/rz/r01uh0437ej0400_rz_a1l.pdf?key=e1025f8b1f10e21cf09b4acf0a1cf028) I also do not see how this would work, because the pins connected to USB port are not multiplexed with the UART RX/TX function (P7_1/P7_2 or P7_5/P7_6). It is possible I am just unable to map the pins correctly...

I also tried going into flash writing mode, but no matter which combination of buttons I press I do not see the LED1 lighting up or down. The two *_SerialBridge projects give different information on what to press to enter the flashing mode (BUTTON0+RESET vs BUTTON1+BUTTON0), but I assume it might depend on the differences in main.cpp file?

It is also unclear to me where to expect the serial connection with ESP32. The instructions say "you need to connect your PC and MicroUSB Connector(RZ/A1 Ch.0)", but I never get this port recognised by the system, even though I am using Windows 10, so I should not need to install any additional software. The Ch.1 connector doesn't work as a serial connection either.

I would much appreciate information on what might be wrong with my set up and how to proceed with accessing ESP32 chip via serial to read out it firmware version and update it.

**Comment by d-kato** [comment]
Hello @michalpasztamobica. I tried using ``GR-LYCHEE_ESP32_Serial_Bridge.bin``. Certainly pressing the RESET button did not enter the flash writing mode. 

I updated REDEME. Please try this way. https://github.com/d-kato/GR-Boards_ESP32_Serial_Bridge/commit/368f4c90f0d9be9e3a7f1879d94f631ffffe1b7c

**Comment by michalpasztamobica** [comment]
@d-kato , thank you for your quick response. 
I tried again, plugging in the USB cable when the BUTTON0 (UB0) was pressed, but still did not get the LED1 to light up. I also tried UB1, to no avail. I can only see LED5 is turned on every time (I assume this is normal behavior).
Perhaps the GR_LYCHEE hardware has been changed since June 2018?
I also wonder about the UART communication - which port should I expect to transmit data - Ch.0 or Ch.1?

**Comment by d-kato** [comment]
@michalpasztamobica , data transfer uses port "Ch.0". How about the following procedure.  

1. Write a program ``GR-LYCHEE_ESP32_Serial_Bridge.bin``. (GR-Boards_ESP32_Serial_Bridge/docs/esp32-at_bin.zip)  
2. Remove all USB cables from GR-LYCHEE.
3. Do one of the following depending on the mode you want to set.  
   **Flash writing mode**: Holding down USER_BUTTON0 and connecting the USB cable to "ch.0".  
   **Normal mode**: Connect the USB cable to "ch.0".  
   https://github.com/d-kato/GR-Boards_ESP32_Serial_Bridge/blob/master/docs/img/usb0_and_button.jpg  

In addition, the method of version check is as follows.  
### How to check the version
Launch in normal mode, not Flash write mode.  
Execute the following command using the terminal software.  
```
AT+GMR
```
Note : Set the linefeed code (sender side) of your terminal software to ``CR+LF``.  

Please refer to here for the connection of terminal software.  
https://github.com/d-kato/GR-Boards_ESP32_Serial_Bridge#serial-setting

Details of ``AT+GMR``  
https://github.com/espressif/esp32-at/blob/master/docs/ESP32_AT_Commands_Set.md#cmd-GMR

**Comment by michalpasztamobica** [comment]
Thank you for your help, @d-kato .
Unfortunately, if I connect Ch.0 to my PC I don't see any changes in the device manager. According to [the instructions](https://os.mbed.com/handbook/USBSerial) I would expect to see an unknown device or a USB/Serial device, but I see neither. I also tried connecting to a Linux machine, but `lsusb` doesn't return any new recognized devices when I plug in the Ch.0 port.

I flashed the precompiled version of `GR-LYCHEE_ESP32_Serial_Bridge.bin` by dragging it to MBED device and then unmounting it.
That method should work, but it doesn't give any confirmation, so I also did
`mbed compile -t ARM -m GR_LYCHEE --flash`
to see the confirmation output:
```
Image: .\BUILD\GR_LYCHEE\ARM\GR-Boards_ESP32_Serial_Bridge.bin
        1 file(s) copied.
```
In either case Ch.0 doesn't seem to cause any changed in the device manager and is not recognized as a serial device neither in Windows nor in Linux.

**Comment by michalpasztamobica** [comment]
In case it matters, the board which I have is marked with X50A-M01C on the back side.
The only schematics I could find seem to refer to [X50A-M01-B](https://www.core.co.jp/solution/m2m/gr-lychee/pdf/history/gr-lychee_circuit_b.pdf). Could that make a difference?

EDIT: sorry, there is also a PDF with [X50A-M01C](https://os.mbed.com/media/uploads/1050186/x50a-m01-c.pdf) schematics. The USB part is identical, so seems like this should not be an issue. My board has R7S721030VC chip soldered.

**Comment by d-kato** [comment]
I also use the X50A-M01C. The schematic can be downloaded from "Schematics" at the following URL.  
https://os.mbed.com/platforms/Renesas-GR-LYCHEE/

It may be a board specific problem.
Do other samples such as "blinky" work correctly? If other samples do not work, try rewriting DAPLink.  
https://armmbed.github.io/DAPLink/?board=GR_LYCHEE

**Comment by michalpasztamobica** [comment]
@d-kato , thank you for this suggestion. The board seems to run fine. 
I already updated DAP-Link firmware to version 0254.

I must say, to my surprise the [blinky example](https://github.com/ARMmbed/mbed-os-example-blinky) didn't work for me, but perhaps it's a matter of setting up LEDs in the json file...

I wouldn't worry about this because I can for example compile and run a pretty complex mbed-os testsuite:
```
mbed test --compile -t ARM -m GR_LYCHEE --app-config mbed_app.wlan0.json -n tests-netsocket-udp -v
 mbed test --run -t ARM -m GR_LYCHEE --app-config mbed_app.wlan0.json -n tests-netsocket-udp -v
```
and get some valid results, including serial outputs:
```
mbedgt: test case summary: 18 passes, 2 failures
mbedgt: all tests finished!
....
mbedgt: test suite report:
| target          | platform_name | test suite          | result | elapsed_time (sec) | copy_method |
|-----------------|---------------|---------------------|--------|--------------------|-------------|
| GR_LYCHEE-ARMC6 | GR_LYCHEE     | tests-netsocket-udp | FAIL   | 80.92              | default     |
mbedgt: test suite results: 1 FAIL
```
This test is however only using the USB Ch.1 (the one situated between ESP32 and the audio jack).

This led me to suspect I am doing something wrong with the Serial_Bridge set up. Could it be some mbed_app.json configuration missing?

**Comment by michalpasztamobica** [comment]
@d-kato , it turned out that the Blink example started working, when I downgraded to 0253 version of DAPLink firmware. 
Then I also managed to get the Ch.0 UART up and running, go into flash mode and check the firmware version of the ESP32.
Somehow the upgraded version worked fine with `mbed test` command and reported no errors when I was flashing other images.
Thank you for your help!
